version: '3.7'

services:
  db:
    build:
      dockerfile: Dockerfile
      context: ./encurtador-url-db
    image: 'encurtador-url-db/postgres:10.5'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=@dm!n'
    volumes:
     - '/data'
  
  api:
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: ./
    image: 'encurtador-url/encurtador-api:latest'
    ports:
      - '8080:8080'
    links:
      - 'db:PSQL'